import { SVGProps } from 'react';

export type Countries =
    // MENA (Middle East and North Africa) - 19 стран
    | 'algeria'
    | 'bahrain'
    | 'egypt'
    | 'iran'
    | 'iraq'
    | 'israel'
    | 'jordan'
    | 'kuwait'
    | 'lebanon'
    | 'libya'
    | 'morocco'
    | 'oman'
    | 'palestine'
    | 'qatar'
    | 'saudi-arabia'
    | 'syria'
    | 'tunisia'
    | 'united-arab-emirates'
    | 'yemen'

    // SEA (Southeast Asia) - 11 стран
    | 'brunei'
    | 'cambodia'
    | 'indonesia'
    | 'laos'
    | 'malaysia'
    | 'myanmar'
    | 'philippines'
    | 'thailand'
    | 'timor-leste'
    | 'vietnam'

    // TIER-1 - 29 стран
    | 'andorra'
    | 'australia'
    | 'austria'
    | 'belgium'
    | 'canada'
    | 'denmark'
    | 'finland'
    | 'france'
    | 'germany'
    | 'greece'
    | 'iceland'
    | 'ireland'
    | 'italy'
    | 'japan'
    | 'liechtenstein'
    | 'luxembourg'
    | 'malta'
    | 'monaco'
    | 'netherlands'
    | 'new-zealand'
    | 'norway'
    | 'portugal'
    | 'san-marino'
    | 'spain'
    | 'sweden'
    | 'switzerland'
    | 'united-kingdom'
    | 'united-states'
    | 'vatican-city'

    // TIER-2 - 19 стран
    | 'albania'
    | 'bosnia-herzegovina'
    | 'bulgaria'
    | 'croatia'
    | 'cyprus'
    | 'czechia'
    | 'estonia'
    | 'hungary'
    | 'latvia'
    | 'lithuania'
    | 'montenegro'
    | 'north-macedonia'
    | 'poland'
    | 'romania'
    | 'serbia'
    | 'slovakia'
    | 'slovenia'
    | 'georgia'
    | 'turkey'

    // TIER-3 - 61 стран
    | 'angola'
    | 'benin'
    | 'botswana'
    | 'burkina-faso'
    | 'burundi'
    | 'cabo-verde'
    | 'cameroon'
    | 'central-african-republic'
    | 'chad'
    | 'comoros'
    | 'congo'
    | 'democratic-republic-congo'
    | 'cote-divoire'
    | 'djibouti'
    | 'equatorial-guinea'
    | 'eritrea'
    | 'eswatini'
    | 'ethiopia'
    | 'gabon'
    | 'gambia'
    | 'ghana'
    | 'guinea'
    | 'guinea-bissau'
    | 'kenya'
    | 'lesotho'
    | 'liberia'
    | 'madagascar'
    | 'malawi'
    | 'mali'
    | 'mauritania'
    | 'mauritius'
    | 'mozambique'
    | 'namibia'
    | 'niger'
    | 'nigeria'
    | 'rwanda'
    | 'sao-tome-principe'
    | 'senegal'
    | 'seychelles'
    | 'sierra-leone'
    | 'somalia'
    | 'south-africa'
    | 'south-sudan'
    | 'sudan'
    | 'tanzania'
    | 'togo'
    | 'uganda'
    | 'zambia'
    | 'zimbabwe'
    | 'fiji'
    | 'kiribati'
    | 'marshall-islands'
    | 'micronesia'
    | 'nauru'
    | 'palau'
    | 'papua-new-guinea'
    | 'samoa'
    | 'solomon-islands'
    | 'tonga'
    | 'tuvalu'
    | 'vanuatu'

    // CIS - 10 стран
    | 'russia'
    | 'uzbekistan'
    | 'kazakhstan'
    | 'belarus'
    | 'turkmenistan'
    | 'kyrgyzstan'
    | 'armenia'
    | 'tajikistan'
    | 'azerbaijan'
    | 'moldova'

    // ASIA - 12 стран
    | 'afghanistan'
    | 'bangladesh'
    | 'bhutan'
    | 'china'
    | 'india'
    | 'maldives'
    | 'mongolia'
    | 'nepal'
    | 'north-korea'
    | 'pakistan'
    | 'south-korea'
    | 'sri-lanka'

    // LATAM - 32 стран
    | 'antigua-barbuda'
    | 'argentina'
    | 'bahamas'
    | 'barbados'
    | 'belize'
    | 'bolivia'
    | 'brazil'
    | 'chile'
    | 'colombia'
    | 'costa-rica'
    | 'cuba'
    | 'dominican-republic'
    | 'ecuador'
    | 'el-salvador'
    | 'grenada'
    | 'guatemala'
    | 'guyana'
    | 'haiti'
    | 'honduras'
    | 'jamaica'
    | 'mexico'
    | 'nicaragua'
    | 'panama'
    | 'paraguay'
    | 'peru'
    | 'saint-kitts-nevis'
    | 'saint-lucia'
    | 'saint-vincent-grenadines'
    | 'suriname'
    | 'trinidad-tobago'
    | 'uruguay'
    | 'venezuela';

export type MapCountry = {
    key: Countries;
    name: string;
    svgPathProps: Omit<
        SVGProps<SVGPathElement>,
        'fill' | 'aria-label' | 'className' | 'onClick'
    >;
};
